"""update unique constraint for all tables

Revision ID: 01b006a55789
Revises: 84956e6c3999
Create Date: 2023-12-03 09:06:24.884030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b006a55789'
down_revision: Union[str, None] = '84956e6c3999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'article_content', ['content'])
    op.create_unique_constraint(None, 'file_content', ['url'])
    op.create_unique_constraint('unique_lesson_question', 'quiz_content', ['lesson_id', 'question'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_lesson_question', 'quiz_content', type_='unique')
    op.drop_constraint(None, 'file_content', type_='unique')
    op.drop_constraint(None, 'article_content', type_='unique')
    # ### end Alembic commands ###
