"""update: add lesson_id to quiz_questions table

Revision ID: 24dab9f78f25
Revises: a9cff2698dc0
Create Date: 2023-11-30 21:43:00.605054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24dab9f78f25'
down_revision: Union[str, None] = 'a9cff2698dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('_lesson_question_uc', 'quiz_questions', ['lesson_id', 'question'])
    op.create_foreign_key(None, 'quiz_questions', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.drop_constraint('_lesson_question_uc', 'quiz_questions', type_='unique')
    op.drop_column('quiz_questions', 'lesson_id')
    # ### end Alembic commands ###
