"""make email field unique in auth model

Revision ID: 2d44906bbc59
Revises: e5091e4a39be
Create Date: 2023-11-17 09:15:51.263353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d44906bbc59'
down_revision: Union[str, None] = 'e5091e4a39be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_login', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_login', type_='unique')
    # ### end Alembic commands ###
