"""update: change content_id to quiz_id in QuizQuestions model

Revision ID: 79b89970c00b
Revises: ebbcf3337cc3
Create Date: 2023-11-27 08:28:10.125325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b89970c00b'
down_revision: Union[str, None] = 'ebbcf3337cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('quiz_id', sa.Integer(), nullable=True))
    op.drop_constraint('quiz_questions_content_id_fkey', 'quiz_questions', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_questions', 'quiz_content', ['quiz_id'], ['id'])
    op.drop_column('quiz_questions', 'content_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.create_foreign_key('quiz_questions_content_id_fkey', 'quiz_questions', 'quiz_content', ['content_id'], ['id'])
    op.drop_column('quiz_questions', 'quiz_id')
    # ### end Alembic commands ###
