"""add created_at and updated_at fields to hashalgorithms model

Revision ID: 7dc9e10e5340
Revises: d262a109a8de
Create Date: 2023-11-15 23:32:13.302067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc9e10e5340'
down_revision: Union[str, None] = 'd262a109a8de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashing_algorithms', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('hashing_algorithms', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hashing_algorithms', 'updated_at')
    op.drop_column('hashing_algorithms', 'created_at')
    # ### end Alembic commands ###
