"""add unique constraint to lesson model

Revision ID: 81fdf465e6cd
Revises: 07e03c733bc5
Create Date: 2023-11-21 06:30:19.648792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fdf465e6cd'
down_revision: Union[str, None] = '07e03c733bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_section_lesson', 'lessons', ['section_id', 'title', 'description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_section_lesson', 'lessons', type_='unique')
    # ### end Alembic commands ###
