"""create user login

Revision ID: 8770ec9670ef
Revises: 
Create Date: 2023-11-13 10:34:53.249943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8770ec9670ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashing_algorithms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('algorithm_name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashing_algorithms_id'), 'hashing_algorithms', ['id'], unique=False)
    op.create_table('user_login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_name', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=250), nullable=True),
    sa.Column('password_salt', sa.String(length=100), nullable=True),
    sa.Column('hash_algorithm_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('confirmation_token', sa.String(length=100), nullable=True),
    sa.Column('token_generation_time', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('password_recovery_token', sa.String(length=100), nullable=True),
    sa.Column('recovery_token_time', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hash_algorithm_id'], ['hashing_algorithms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_login_id'), 'user_login', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_login_id'), table_name='user_login')
    op.drop_table('user_login')
    op.drop_index(op.f('ix_hashing_algorithms_id'), table_name='hashing_algorithms')
    op.drop_table('hashing_algorithms')
    # ### end Alembic commands ###
