"""add unique ordering contstraint to lessons

Revision ID: 979f3344d68d
Revises: b8565af9f784
Create Date: 2023-11-21 07:28:00.652804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979f3344d68d'
down_revision: Union[str, None] = 'b8565af9f784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_section_lesson', 'lessons', type_='unique')
    op.create_unique_constraint('_course_section_ordering_uc', 'lessons', ['course_id', 'section_id', 'ordering'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_course_section_ordering_uc', 'lessons', type_='unique')
    op.create_unique_constraint('unique_section_lesson', 'lessons', ['section_id', 'course_id', 'title', 'description'])
    # ### end Alembic commands ###
