"""update models

Revision ID: ac9122f3a039
Revises: 5be05d8d81da
Create Date: 2023-11-20 21:28:46.436082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac9122f3a039'
down_revision: Union[str, None] = '5be05d8d81da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_providers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('external_providers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('external_user_auth', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('external_user_auth', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('hashing_algorithms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('hashing_algorithms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('user_permissions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_permissions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('user_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('user_permissions', 'updated_at')
    op.drop_column('user_permissions', 'created_at')
    op.alter_column('hashing_algorithms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('hashing_algorithms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('external_user_auth', 'updated_at')
    op.drop_column('external_user_auth', 'created_at')
    op.drop_column('external_providers', 'updated_at')
    op.drop_column('external_providers', 'created_at')
    # ### end Alembic commands ###
