"""add unique constraint to lesson model

Revision ID: b8565af9f784
Revises: 81fdf465e6cd
Create Date: 2023-11-21 07:19:24.226750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8565af9f784'
down_revision: Union[str, None] = '81fdf465e6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_section_lesson', 'lessons', type_='unique')
    op.create_unique_constraint('unique_section_lesson', 'lessons', ['section_id', 'course_id', 'title', 'description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_section_lesson', 'lessons', type_='unique')
    op.create_unique_constraint('unique_section_lesson', 'lessons', ['section_id', 'title', 'description'])
    # ### end Alembic commands ###
