"""update: question_text to text in QuizQuestion

Revision ID: bf42b5d817be
Revises: 79b89970c00b
Create Date: 2023-11-27 08:32:41.731767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf42b5d817be'
down_revision: Union[str, None] = '79b89970c00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('text', sa.Text(), nullable=False))
    op.drop_column('quiz_questions', 'question_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('quiz_questions', 'text')
    # ### end Alembic commands ###
