"""update email verification table

Revision ID: cbe0dc4bc3f9
Revises: 62ffcc00e18a
Create Date: 2023-11-14 10:21:19.929856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe0dc4bc3f9'
down_revision: Union[str, None] = '62ffcc00e18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification', sa.Column('is_used', sa.Boolean(), nullable=True))
    op.drop_column('user_login', 'token_generation_time')
    op.drop_column('user_login', 'confirmation_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('confirmation_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_login', sa.Column('token_generation_time', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('email_verification', 'is_used')
    # ### end Alembic commands ###
