"""add updated at field to userlogin model

Revision ID: d262a109a8de
Revises: fd81e91d97ba
Create Date: 2023-11-15 23:31:12.104336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd262a109a8de'
down_revision: Union[str, None] = 'fd81e91d97ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_login', 'updated_at')
    # ### end Alembic commands ###
