"""make permission_name unique

Revision ID: d2800f26b4d2
Revises: bb0debff01e4
Create Date: 2023-11-18 15:41:25.095581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2800f26b4d2'
down_revision: Union[str, None] = 'bb0debff01e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_permissions', 'permission_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'user_permissions', ['permission_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_permissions', type_='unique')
    op.alter_column('user_permissions', 'permission_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
