"""update: make foreign keys not nullable

Revision ID: e1538b8bdc36
Revises: 24dab9f78f25
Create Date: 2023-11-30 22:14:54.170652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1538b8bdc36'
down_revision: Union[str, None] = '24dab9f78f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_questions', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quiz_questions', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_questions', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quiz_questions', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
