"""fix constraint errors

Revision ID: e49dd5319c5a
Revises: 979f3344d68d
Create Date: 2023-11-21 08:28:38.100401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49dd5319c5a'
down_revision: Union[str, None] = '979f3344d68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_section_lesson', 'lessons', ['section_id', 'course_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_section_lesson', 'lessons', type_='unique')
    # ### end Alembic commands ###
