"""update hashalgorithms model

Revision ID: e5091e4a39be
Revises: 7dc9e10e5340
Create Date: 2023-11-16 00:11:39.182172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5091e4a39be'
down_revision: Union[str, None] = '7dc9e10e5340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
