"""add options to QuizQuestions model

Revision ID: e7435e943049
Revises: 4de50eeab87c
Create Date: 2023-11-25 07:38:06.609731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7435e943049'
down_revision: Union[str, None] = '4de50eeab87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_question', sa.Column('options', sa.JSON(), nullable=True))
    op.drop_column('quiz_question', 'updated_at')
    op.drop_column('quiz_question', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_question', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('quiz_question', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('quiz_question', 'options')
    # ### end Alembic commands ###
