"""add external provider table

Revision ID: f4d57c12122f
Revises: cbe0dc4bc3f9
Create Date: 2023-11-14 10:39:48.005556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d57c12122f'
down_revision: Union[str, None] = 'cbe0dc4bc3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=True),
    sa.Column('web_service_endpoint', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_providers_id'), 'external_providers', ['id'], unique=False)
    op.create_table('external_user_login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('provider_token', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['external_providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_login.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_user_login_id'), 'external_user_login', ['id'], unique=False)
    op.drop_column('user_login', 'login_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('login_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_external_user_login_id'), table_name='external_user_login')
    op.drop_table('external_user_login')
    op.drop_index(op.f('ix_external_providers_id'), table_name='external_providers')
    op.drop_table('external_providers')
    # ### end Alembic commands ###
